### ISSUE TITLE
Could not find Makefile+Call Stack (most recent call first):   CMakeLists.txt:151 (add_core)

### ISSUE THREAD

**Issue by reginalluna** [openai/retro#199]
## Issue summary

I tried many times to build [retro] through CMake, but the error is keep showing up. I don't know how to fix them.
![image](https://user-images.githubusercontent.com/54960230/76565957-26574100-6482-11ea-9ac3-b21a69a8815f.png)

![image](https://user-images.githubusercontent.com/54960230/76566050-54d51c00-6482-11ea-9f60-3e43f4e8ae00.png)

[Put a detailed description of the issue here.]

## System information

- [Operating system]:  Windows10
- [Python version]:  3.8
- [Gym Retro version]: the newest

**Comment by endrift** [comment]
You need to do a proper git checkout, this looks like you downloaded and extracted a zip file of the repository

**Comment by reginalluna** [comment]
> You need to do a proper git checkout, this looks like you downloaded and extracted a zip file of the repository

Hi endriftm

I used GitDesktop to clone this repository. About the git checkout, which branch should I get in?

**Comment by reginalluna** [comment]
> You need to do a proper git checkout, this looks like you downloaded and extracted a zip file of the repository

And now I'm having the problem like this 
![image](https://user-images.githubusercontent.com/54960230/76653379-ee620380-653e-11ea-9c80-257619b2baea.png)

**Comment by christopherhesse** [comment]
It looks like your python may also be broken.  You may want to reinstall python.

If you follow the instructions for building from source here: https://retro.readthedocs.io/en/latest/developing.html building retro should work (but the instructions are not extensively tested).

Can I ask why you are installing retro from source?  Most users do not need to do this.

**Comment by reginalluna** [comment]
> It looks like your python may also be broken. You may want to reinstall python.
> 
> If you follow the instructions for building from source here: https://retro.readthedocs.io/en/latest/developing.html building retro should work (but the instructions are not extensively tested).
> 
> Can I ask why you are installing retro from source? Most users do not need to do this.

Hi Christopherhesse,

I'm confused about the instruction of using Gym-Retro (I'm an artist so I don't have that much knowledge about computer science hope you don't mind.) 

I'm following the tutorial https://www.youtube.com/watch?v=CFa6NhLgeL0 here, and I'm stopping at 
```
pip3 install -e .
```
for three days.

**Comment by reginalluna** [comment]
> It looks like your python may also be broken. You may want to reinstall python.
> 
> If you follow the instructions for building from source here: https://retro.readthedocs.io/en/latest/developing.html building retro should work (but the instructions are not extensively tested).
> 
> Can I ask why you are installing retro from source? Most users do not need to do this.

Should I uninstall all the python on my computer?

**Comment by christopherhesse** [comment]
I'm afraid we don't really provide python support here, but you should probably uninstall and reinstall all the pythons.

I took a quick look at that video and I don't know why the person installs retro from source, I think you could accomplish the same thing by following the getting started guide here: https://retro.readthedocs.io/en/latest/getting_started.html and then doing the `import_sega_classics` script mentioned in the video to get the sonic ROM installed.

Installing from source if you don't have to do it will be a huge pain.

**Comment by reginalluna** [comment]
> I'm afraid we don't really provide python-support here, but you should probably uninstall and reinstall all the pythons.
> 
> I took a quick look at that video and I don't know why the person installs retro from source, I think you could accomplish the same thing by following the getting started guide here: https://retro.readthedocs.io/en/latest/getting_started.html and then doing the `import_sega_classics` script mentioned in the video to get the sonic ROM installed.
> 
> Installing from source if you don't have to do it will be a huge pain.

Hi Christopherhess,

Thanks so much for your advice. I'm uninstalling all the python stuff first and follow the step you provide. I will let you know if I find any trouble next. xxx

**Comment by reginalluna** [comment]
> I'm afraid we don't really provide python support here, but you should probably uninstall and reinstall all the pythons.
> 
> I took a quick look at that video and I don't know why the person installs retro from source, I think you could accomplish the same thing by following the getting started guide here: https://retro.readthedocs.io/en/latest/getting_started.html and then doing the `import_sega_classics` script mentioned in the video to get the sonic ROM installed.
> 
> Installing from source if you don't have to do it will be a huge pain.

Hi Christopherhess,

it doesn't work when I typed
```
pip install -e .
```
![image](https://user-images.githubusercontent.com/54960230/76662971-f2e5e680-6555-11ea-8c9e-819e82601849.png)

Do I make anything wrong there?
---
I tried to follow the instruction on getting_started but I'm confusing about the way to creat <Create a Gym Environment>. Where should I put 
```
import retro
env = retro.make(game='Airstriker-Genesis')
```

**Comment by reginalluna** [comment]
> I'm afraid we don't really provide python support here, but you should probably uninstall and reinstall all the pythons.
> 
> I took a quick look at that video and I don't know why the person installs retro from source, I think you could accomplish the same thing by following the getting started guide here: https://retro.readthedocs.io/en/latest/getting_started.html and then doing the `import_sega_classics` script mentioned in the video to get the sonic ROM installed.
> 
> Installing from source if you don't have to do it will be a huge pain.

Hi Christopherhess,

When I run ```pip install gym-retro``` the problem shows up.
![image](https://user-images.githubusercontent.com/54960230/76663419-3d1b9780-6557-11ea-9a76-975c39c516d9.png)

**Comment by christopherhesse** [comment]
Oh, we don't have python 3.8 wheels yet, you should make sure you are using python 3.7

**Comment by reginalluna** [comment]
Oh no. My fault. Let me install Python 3.7; btw, could I keep Python 3.8 on
my device?

**Comment by christopherhesse** [comment]
Maybe but it's going to be pretty confusing if you do.

**Comment by reginalluna** [comment]
> I'm afraid we don't really provide python support here, but you should probably uninstall and reinstall all the pythons.
> 
> I took a quick look at that video and I don't know why the person installs retro from source, I think you could accomplish the same thing by following the getting started guide here: https://retro.readthedocs.io/en/latest/getting_started.html and then doing the `import_sega_classics` script mentioned in the video to get the sonic ROM installed.
> 
> Installing from source if you don't have to do it will be a huge pain.

I tried to run ```pip3 install -e . ``` on LinuxOS, but it doesn't work still.

**Comment by reginalluna** [comment]
> > I'm afraid we don't really provide python support here, but you should probably uninstall and reinstall all the pythons.
> > I took a quick look at that video and I don't know why the person installs retro from source, I think you could accomplish the same thing by following the getting started guide here: https://retro.readthedocs.io/en/latest/getting_started.html and then doing the `import_sega_classics` script mentioned in the video to get the sonic ROM installed.
> > Installing from source if you don't have to do it will be a huge pain.
> 
> I tried to run `pip3 install -e . ` on LinuxOS, but it doesn't work still.

Ok, the code ```sudo apt-get install zlib1g-dev``` did help. Let me see if it can run well or not.

**Comment by christopherhesse** [comment]
I think you should probably not run `pip install -e` at all.  As the getting started guide says, you should probably run `pip3 install gym-retro`

**Comment by reginalluna** [comment]
> I think you should probably not run `pip install -e` at all. As the getting started guide says, you should probably run `pip3 install gym-retro`

It works on the Ubuntu (VM), but O'm still not sure whether it can work on windows10 or not.

Here' the new problem I have => 'module' object has no attribute 'make'

**Comment by christopherhesse** [comment]
`pip install gym-retro` should work on windows, I use it on my windows 10 machine, and I've never gotten retro to build from source on there.  It won't work with python 3.8 though, just 3.7 and 3.6, until this issue is fixed: https://github.com/openai/retro/issues/197

**Comment by reginalluna** [comment]
> `pip install gym-retro` should work on windows, I use it on my windows 10 machine, and I've never gotten retro to build from source on there. It won't work with python 3.8 though, just 3.7 and 3.6, until this issue is fixed: #197

```pip install gym-retro``` can work on windows 10, but when I use ```pip3 install -e .``` it causes a crushing. Let me try to run it on Ubuntu first then check it on win10 later.

**Comment by christopherhesse** [comment]
I am saying don't use `pip3 install -e`

**Comment by reginalluna** [comment]
> I am saying don't use `pip3 install -e`

Oh, ok. It works on Ubuntu anyway. But, I'm having a new proble of AttributeError: 'module' object has no attribute 'make'
now

**Comment by christopherhesse** [comment]
You're probably in some folder that has a folder named `retro` in it, change to a different directory.

**Comment by christopherhesse** [comment]
Closing due to lack of activity
